image: alpine/edge
packages:
  - go
sources:
  - https://github.com/emersion/go-msgauth
artifacts:
  - coverage.html
tasks:
  - build: |
      cd go-msgauth
      go build -v ./...
  - test: |
      cd go-msgauth
      go test -coverprofile=coverage.txt -covermode=atomic ./...
  - coverage: |
      cd go-msgauth
      go tool cover -html=coverage.txt -o ~/coverage.html
